#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
systemctl restart nginx
